Bump Python `pyyaml` package dependency to 6.0.3
The previous version is incompatible with Python 3.14, which caused Poetry commands to fail after updating the project's
Python version:

```
- Installing pyyaml (5.4.1)

[...]

| AttributeError: 'build_ext' object has no attribute 'cython_sources'
```