Add missing task dependency to template installation docs
The `poetry:install` task calls the `utility:normalize-path` task. So this task is a dependency of all templates that
use the `poetry:install` task.

Previously, the installation instructions for these templates did not specify the addition of the
`utility:normalize-path` task to the project's taskfile. This resulted in a spurious failure of the `poetry:install`
task, with a cryptic error:

```
task: Task "utility:normalize-path" does not exist
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\per\AppData\Roaming\Python\Python312\Scripts\pipx.exe\__main__.py", line 4, in <module>
    from pipx.main import cli
  File "C:\Users\per\AppData\Roaming\Python\Python314\site-packages\pipx\main.py", line 22, in <module>
    from pipx import commands, constants, paths
  File "C:\Users\per\AppData\Roaming\Python\Python314\site-packages\pipx\commands\__init__.py", line 2, in <module>
    from pipx.commands.environment import environment
  File "C:\Users\per\AppData\Roaming\Python\Python314\site-packages\pipx\commands\environment.py", line 6, in <module>
    from pipx.interpreter import DEFAULT_PYTHON
  File "C:\Users\per\AppData\Roaming\Python\Python314\site-packages\pipx\interpreter.py", line 184, in <module>
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
  File "C:\Users\per\AppData\Roaming\Python\Python314\site-packages\pipx\interpreter.py", line 175, in _get_absolute_python_interpreter
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
  File "C:\Users\per\AppData\Roaming\Python\Python314\site-packages\pipx\interpreter.py", line 175, in _get_absolute_python_interpreter
    raise PipxError(f"Default python interpreter '{env_python}' is invalid.")
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
  File "C:\Users\per\AppData\Roaming\Python\Python314\site-packages\pipx\interpreter.py", line 175, in _get_absolute_python_interpreter
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
    DEFAULT_PYTHON = _get_absolute_python_interpreter(env_default_python)
  File "C:\Users\per\AppData\Roaming\Python\Python314\site-packages\pipx\interpreter.py", line 175, in _get_absolute_python_interpreter
    raise PipxError(f"Default python interpreter '{env_python}' is invalid.")
pipx.util.PipxError: Default python interpreter 'task: Available tasks for this project: * check:                          Check for problems with the project * fix:                            Make automated corrections to
the project's files * docs:generate:                  Create all generated documentation content * general:check-formatting:       Check basic formatting style of all files * general:format-prettier:
Format all supported files with Prettier * markdown:check-links:           Check for broken links * markdown:fix:                   Automatically correct linting violations in Markdown files where
possible * markdown:lint:                  Check for problems in Markdown files * npm:install-deps:               Install dependencies managed by npm. Environment variable parameters: - PROJECT_PATH: Path
of the npm-managed project (default: .).  * poetry:install:                 Install Poetry * poetry:install-deps:            Install dependencies managed by Poetry. Environment variable parameters: -
POETRY_GROUPS: Poetry dependency groups to install (default: install all dependencies).  * python:format:                  Format Python files * python:lint:                    Lint Python code' is
invalid.
task: Failed to run task "poetry:install": exit status 1
```