Install referenced schema in "eslint:validate" task
The "eslint:validate" task validates the repository's ESLint configuration file against its JSON schema to catch any
problems with its data format.

In order to avoid duplication of content, JSON schemas may reference other schemas via the `$ref` keyword. The
ESLint configuration file schema was recently updated to share resources with a separate ESLint plugins configuration
schema, which caused the validation to start failing:

schema /tmp/eslintrc-schema-usLlcKrt8g.json is invalid
error: can't resolve reference https://json.schemastore.org/partial-eslint-plugins.json from id https://json.schemastore.org/eslintrc.json#
task: Failed to run task "eslint:validate": exit status 1

The solution is to configure the task to download that schema as well and also to provide its path to the avj-cli
validator via a `-r` flag.