Install referenced schema in "dependabot:validate" task
The "dependabot:validate" task validates the repository's `package.json` npm manifest file against its JSON schema to
catch any problems with its data format.

In order to avoid duplication of content, JSON schemas may reference other schemas via the `$ref` keyword. The
Dependabot configuration schema was recently updated to share resources with the "base" configuration schema, which
caused the validation to start failing:

schema /tmp/dependabot-schema-CuMFs6bqY1.json is invalid
error: can't resolve reference https://json.schemastore.org/base.json#/definitions/timezone from id https://json.schemastore.org/timezone

The solution is to configure the task to download that schema as well and also to provide its path to the avj-cli
validator via a `-r` flag.