Use Go 1.27.1 for Go release builds
Several changes were required to accompany the Go version bump:

Image Names
-----------

A Debian 10 variant of the `docker.elastic.co/beats-dev/golang-crossbuild` Linux ARMv6 image is no longer available:

```
docker: Error response from daemon: manifest for docker.elastic.co/beats-dev/golang-crossbuild:1.27.1-armel-debian10 not found: manifest unknown: manifest unknown
```

So it was necessary to update the image used for the Linux ARMv6 to Debian 12.

The format of the tag name for the `docker.elastic.co/beats-dev/golang-crossbuild` Linux ARM 64-bit image has changed:

```
docker: Error response from daemon: manifest for docker.elastic.co/beats-dev/golang-crossbuild:1.27.1-arm not found: manifest unknown: manifest unknown
```

This made it necessary to change the name of the image used for the Linux ARM 64-bit release build to `docker.elastic.co/beats-dev/golang-crossbuild:1.27.1-base-arm-debian10`.

Configure Git to permit "dubious ownership" of project repository
-----------------------------------------------------------------

As a security measure (see CVE-2022-24765), starting from 2.30.3 Git requires the repository folder to be owned by the
operating system user's account. Due to it having been checked out outside the container, the repository does not meet
this requirement inside the container. Previous versions of the image used an older version of Git, so this was not a
problem before the bump, but a newer version is used by the Go image. This, causes the build to:

```
error obtaining VCS status: exit status 128
  Use -buildvcs=false to disable VCS stamping.
Error: failed building for linux/armv6: exit status 1
failed building for linux/armv6: exit status 1
task: Failed to run task "dist:Linux_ARMv6": exit status 1
```

The solution is to configure the Git installation in the build container to allow the use of the repository, despite the
"dubious ownership" of its folder. This is done via the `safe.directory` Git configuration variable.

Runner for ARM Release Builds
-----------------------------

Previously, the Go release workflows used the `ubuntu-latest` GitHub Actions runner for all release builds. However,
modern versions of the `docker.elastic.co/beats-dev/golang-crossbuild` image fail when an ARM variant of the image is
used on a non-ARM host machine:

```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /crossbuild: exec format error
```

The incompatibility is solved by using a Linux ARM runner for the matrix jobs building for ARM targets.

The alternative would be emulation via QEMU (which can be accomplished by simply installing QEMU on the runner via the
"docker/setup-qemu-action" action). However, using a native ARM machine will be more efficient.

It is standard practice to use the "latest" GitHub Actions runner identifiers in the project's workflows, which causes
the workflow runs to always use the newest stable runner version. However, GitHub has broken from this established
convention by choosing to not provide "latest" identifiers for the Linux ARM runners. For this reason, the
version-specific runner name `ubuntu-26.04-arm` had to be used in the workflow. It will be necessary to manually update
the runner name as new stable versions are made available (or more likely fail to do so until forced after GitHub's
removal of the runner in use breaks the workflows).